-- Multiple assignees per task: Task.assigneeId becomes the task_assignees join
-- table. Generated by `prisma migrate diff`, then REORDERED by hand so every
-- existing assignee is copied across before the column is dropped.
-- docs/api/task.md §Assignees.

-- CreateTable
CREATE TABLE "task_assignees" (
    "taskId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "task_assignees_pkey" PRIMARY KEY ("taskId","userId")
);

-- CreateIndex
CREATE INDEX "task_assignees_userId_idx" ON "task_assignees"("userId");

-- AddForeignKey
ALTER TABLE "task_assignees" ADD CONSTRAINT "task_assignees_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "task_assignees" ADD CONSTRAINT "task_assignees_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Hand-written: carry every current assignee over. Stamped with the task's
-- updatedAt, the closest record of when the assignment was made.
INSERT INTO "task_assignees" ("taskId", "userId", "createdAt")
SELECT "id", "assigneeId", "updatedAt" FROM "tasks" WHERE "assigneeId" IS NOT NULL;

-- DropForeignKey
ALTER TABLE "tasks" DROP CONSTRAINT "tasks_assigneeId_fkey";

-- DropIndex
DROP INDEX "tasks_assigneeId_idx";

-- AlterTable
ALTER TABLE "tasks" DROP COLUMN "assigneeId";
