-- Backlog essentials: task type, story points, manual rank, comment edits and
-- task activity history. Generated by `prisma migrate diff`, plus ONE
-- hand-written statement at the end (the rank backfill). docs/api/task.md.

-- CreateEnum
CREATE TYPE "TaskType" AS ENUM ('TASK', 'STORY', 'BUG', 'EPIC');

-- AlterTable
ALTER TABLE "tasks" ADD COLUMN     "position" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "storyPoints" INTEGER,
ADD COLUMN     "type" "TaskType" NOT NULL DEFAULT 'TASK';

-- AlterTable
ALTER TABLE "task_comments" ADD COLUMN     "editedAt" TIMESTAMP(3);

-- CreateTable
CREATE TABLE "task_activities" (
    "id" TEXT NOT NULL,
    "taskId" TEXT NOT NULL,
    "actorId" TEXT,
    "action" TEXT NOT NULL,
    "field" TEXT,
    "from" JSONB,
    "to" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "task_activities_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "task_activities_taskId_createdAt_idx" ON "task_activities"("taskId", "createdAt");

-- CreateIndex
CREATE INDEX "tasks_projectId_position_idx" ON "tasks"("projectId", "position");

-- AddForeignKey
ALTER TABLE "task_activities" ADD CONSTRAINT "task_activities_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "task_activities" ADD CONSTRAINT "task_activities_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;


-- Backfill: every existing task gets a rank matching the order the backlog
-- already showed (creation order, which `number` follows), spaced 1024 apart
-- so the first moves have room to take a midpoint. Without this every row is
-- position 0 and the first reorder has no neighbours to split between.
UPDATE "tasks" SET "position" = "number" * 1024;
